management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
      base-path: /actuator
  endpoint:
    metrics:
      enabled: 'true'
    prometheus:
      enabled: 'true'
    health:
      show-details: ${HEALTH:always}
spring:
  jpa:
    database-platform: ${DB_PLATAFORM:org.hibernate.dialect.H2Dialect}
    database: ${DB:h2}
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA_DB:}
  application:
    name: ${APP_NAME:backend}
  datasource:
    password: ${DB_PASS:password}
    username: ${DB_USER:sa}
    url: ${DB_URL:jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DRIVER_CLASS_NAME:org.h2.Driver}
server:
  port: ${PORT:6565}
