management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
      base-path: /actuator
  endpoint:
    metrics:
      enabled: 'true'
    prometheus:
      enabled: 'true'
    health:
      show-details: always
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema:
  application:
    name: backend
  datasource:
    password: password
    username: sa
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
server:
  port: 8080